on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Issue key'
        required: true
      jira-token:
        description: 'JIRA token'
        required: true
      firstname:
        description: 'First name'
        required: true
      lastname:
        description: 'Last name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check User
        env:
          KEY: ${{ github.event.inputs.key }}
          FIRSTNAME: ${{ github.event.inputs.firstname }}
          LASTNAME: ${{ github.event.inputs.lastname }}
          JOBTITLE: ${{ github.event.inputs.title }}
        run: |
          CLIENT_ID=${{ vars.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          
          TOKEN=$(curl -X POST \
          -H "Host: login.microsoftonline.com" \
          -H "Content-type: application/x-www-form-urlencoded" \
          https://login.microsoftonline.com/0496c0c5-5b34-4de0-a252-686f82ec384f/oauth2/v2.0/token \
          -d "client_id=$CLIENT_ID&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
          | jq -r .access_token)

          echo "Got the request.."
          echo "Trying to Trigger.."

          response=$(curl -X GET -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          "https://graph.microsoft.com/v1.0/users?$select=userPrincipalName")
          

          USER=$(echo "$FIRSTNAME.$LASTNAME" | tr '[:upper:]' '[:lower:]')

          if echo "$response" | grep -q "\"$USER@kencamarador.com\""; then
              echo "User $USER@kencamarador.com exists."
              curl -X POST -H 'Content-type: application/json' \
              --data "{\"issues\":[\"$KEY\"], \"message\":\"$USER@kencamarador.com already exists\"}" \
              https://automation.atlassian.com/pro/hooks/efa83076d8f6078839ac388c4ef79493eb86ede4?issue=$KEY
          else
              echo "User $USER@kencamarador.com does not exist."
              curl -X POST -H 'Content-type: application/json' \
              --data "{\"issues\":[\"$KEY\"], \"message\":\"$USER@kencamarador.com does not exists\"}" \
              https://automation.atlassian.com/pro/hooks/11a6f7549365dd41573bb93363e9e3fea9555ab4?issue=$KEY
          fi


