on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Issue key'
        required: true
      jira-token:
        description: 'JIRA token'
        required: true
      firstname:
        description: 'First name'
        required: true
      lastname:
        description: 'Last name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check User
        env:
          KEY: ${{ github.event.inputs.key }}
          FIRSTNAME: ${{ github.event.inputs.firstname }}
          LASTNAME: ${{ github.event.inputs.lastname }}
          JOBTITLE: ${{ github.event.inputs.title }}
        run: |
          echo "hi"
