on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check User
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          JOBTITLE: ${{ github.event.client_payload.title }}
        run: |
          echo "hi"
